#! /usr/bin/env python

data = """
uosnxmfkezbojfdgwvrtaqhluy
iosnxmfkazbcopdgnvrtaqhluy
ioanxmfkezbcjpdgwvrjaohluy
uosnxmfkezbcjpjgwvrtaqhlut
imsnxmfkezbcjpugwvataqhluy
ioenxmfkezbcjpdgwvrraqhluz
iosnxmfkezbcjpdgevitnqhluy
iosnxmfkezcccpdgcvrtaqhluy
loinxmfkezbcjpdgwvrtaqhluu
iosnlmfkezbczndgwvrtaqhluy
iosnxmfkezbcjpdgwvrifghluy
iosnuhfkezbcjpugwvrtaqhluy
iosnxmfkezbcwpdgwvrtaihlgy
iosnxzfwuzbcjpdgwvrtaqhluy
hosnxmfjizbcjpdgwvrtaqhluy
iornxmfktzbcjpdgwvrtaqhluo
nosnxmfkdzbcjpdgwvrtaqhlwy
iosnxmfkezbcjpdgwvrtaktluq
ioszxmlkezbcjvdgwvrtaqhluy
ionnxmfkezbcfpdgwvbtaqhluy
iosnxmfkezrcjedgwvrtaqhluq
irsnxmfkezbcjpdqwvrtafhluy
ioshxmzkezbccpdgwvrtaqhluy
iosnxmfkezbrjpdgwvothqhluy
bosnxmfkezbcbpdgwvrtnqhluy
iosnomfkszbcjpcgwvrtaqhluy
iosnxmflezbcjpdgwvrtaqmuuy
iobnxmfkezbcjpdgxvrtaqfluy
ioenxmfvezbcjgdgwvrtaqhluy
iosnxmfkekbcjprgwvrtaqhlty
iosnumfkezbcjpmgwvrtaqhlmy
ionnxufkezbcjpdgwvrqaqhluy
tosnxmfbezbcjpdghvrtaqhluy
iosnxmfktzbcjpogwmrtaqhluy
iosnamfkezbjjpdgtvrtaqhluy
iosnemfkezmcjpdgwvrtaqhlry
losnxmfkezbcjpdxwvrtaqsluy
fomnxmekezbcjpdgwvrtaqhluy
rosnxmfkezbcjzdcwvrtaqhluy
iosngmrkezbcjpdgwvrtaqhduy
iosnxmaaebbcjpdgwvrtaqhluy
xosnxmfkezbcjpdgwvrmrqhluy
iosnxmfkgzbujpdgwhrtaqhluy
iosnxmekecbcjpmgwvrtaqhluy
mesnxmfdezbcjpdgwvrtaqhluy
insnxmbkezbcjpdgwvrtgqhluy
iosyxmfkezbcjpdgwirtavhluy
iosnxmfkezbcjpdgwlvtjqhluy
iosnxmtkezbcjpdgwvjtaqhlut
iosnxmfkezbsjpdhwvrtaqaluy
iosnumfkezbcjpfgwvrtaqhlfy
iosnxmekezbcdpxgwvrtaqhluy
iosnfmfkezbcjpdgavctaqhluy
iosnxmfkezvcjpdgfvrtamhluy
iovnxmfkezbcjpdgzvrtaqhzuy
iosnbmfkuzbcjpdgwvrtaqhlux
iosnxmfkezbcjpdgwvftauhluc
iosmbmfkezbcmpdgwvrtaqhluy
ifsnxmfvezbcjpdgwvrwaqhluy
iosnxmfkezfcjpdgwvrmaqhyuy
iospxmfkezbcjpdkwvytaqhluy
issnxmfkyzbcjpdgwyrtaqhluy
iosnxmfkezbcjpdbwvrtjqhluz
iosnxmfkwzbcjpdgfvrtajhluy
iosnxmfkezbcjndgwvrnaqxluy
iosnxmfkezbcjpdgwvltawwluy
iosnxmfkezbcjpdguvrtwqhtuy
iornxmfkezbcjpdgwertaihluy
iofdxmokezbcjpdgwvrtaqhluy
iosnxmfkezbcjpdgwgrtiqdluy
iosnxmfkenbcjpdgwqrtiqhluy
iosnxmfkezbcjpugwvotcqhluy
iksnxmfkezbcjfdgqvrtaqhluy
iasnxmfkezbcjpdgwvrtaqheuo
iosnxmfkehbcipdgwvrtaqtluy
iosnxifkezbajpdgwvrtaahluy
iosnxmpkezbccpdguvrtaqhluy
ioinxnfkezbcjpdgwvgtaqhluy
gosnxmfkezbcjpdgwvrtvqkluy
iolnxmfcezbcjpdgwvrtaqhlgy
iosnxmfkezbcppdgwortjqhluy
iesnxafkezbcjpdgwvrtayhluy
iqsnxmfxazbcjpdgwvrtaqhluy
cosnxmfkezbcjpdgwvrtkahluy
ioenxmfkezbcjpdgwvrtzqyluy
iosnxmhkwzbcjpdgwvrtabhluy
iosnxmfkezbcjpdtwvrhaqiluy
iisnxmfkezbcvpdwwvrtaqhluy
iosnsmfkeobcjpdgfvrtaqhluy
iwsnxmfkfzbcjpugwvrtaqhluy
iosnxmflezbcjpdgwvrtaspluy
gosnimfkezbcjpdgwvrtjqhluy
iosnxmfkfibcjmdgwvrtaqhluy
iosnxmfkpzbcjpdgwvitaqhwuy
ionnxmfkerbcjpjgwvrtaqhluy
iosnxmfkezecjgdgwvrtaqhljy
iosnxufkezbcjpdguvltaqhluy
vosnzmfkezbcjpdvwvrtaqhluy
iolnxmfkecbcjpdgwvrtaqpluy
iosnxmfkezbcjpdgwortaqhouw
iomnxmfkezbckpdgwvrtaqhluu
iopnymfkezbchpdgwvrtaqhluy
iosnxmfkezhcjpdguvrtaqhnuy
iosfxmfkezecjpdgyvrtaqhluy
iopnxmfkgzbcjpdgwvbtaqhluy
tosnxmffezbcjpdgwvttaqhluy
iosnxmfkpabcjpdywvrtaqhluy
iosrxmfkekbcjpdgwvrtaqrluy
iosnxmokezbcjpdjwvrtaxhluy
iolnxmfkezbccpdgwvetaqhluy
iosnxmfketecjpdgwvrtaqnluy
iosnxmfkxzbtjpdgwvroaqhluy
ioinxmfkezbcjpdqwvrtjqhluy
iosnxmfkqzbcjpdgwvrtaqzluz
iosnxmfklzbcjpdgwwrtaqhluh
iosnxmfkezbcjpdtwvrtmqhlpy
iosnomfqezgcjpdgwvrtaqhluy
iosnxmfkezbcjodgwvutaqhduy
iosnxmfkezbcjppgwertaqhluu
iosnxmfkezbcjqdggvrtaqhluw
iosnxmvkezbcjpdgwvrtlqfluy
icsnwmfkezbcjpdiwvrtaqhluy
iosnxxbkezbhjpdgwvrtaqhluy
ioknxmfkezacjpdgwvrtaqhliy
iosgxmfkezbcjpdgevrtpqhluy
iosnxmfkezbejpdgwlrtaqhldy
iosnxyfkezbcjpdowvrtaqhlur
iosnxmfkezbcjpnjwvrtaqhlvy
iosnxglkezbcjpdvwvrtaqhluy
iosnxmpkezbcjpdgwvrtxqhlub
iosnxsfwezbcjpdgwmrtaqhluy
aosnxmfkezbcjpdgwvrtaqhpwy
iopnxmqkkzbcjpdgwvrtaqhluy
iosnxmfkewbcfpdgwvrtaqmluy
iosnxmfkekbcjpdgwvltawhluy
iosnxmfmezbcjpdgwvitaqtluy
iosnomfkezbcjpggwvrtaqhlly
iobnkmfkezbcjpdywvrtaqhluy
yosnxmfkezbcjydgwvrtarhluy
iosnxifkezbckpdgyvrtaqhluy
iornxmfkezbcjpduwvreaqhluy
ivsfxmfjezbcjpdgwvrtaqhluy
iosnxmfkezbcspdgwartaqhlui
iosnxmfkezbcjpdgasstaqhluy
iosnxmfkezbajpdgwvrtaqmlux
gzsnxmfkezxcjpdgwvrtaqhluy
iosnxmikczbcjpdgwvrtyqhluy
iosnxmgkezbcjvdgwdrtaqhluy
iosnxpfkezbcjpdgwvrbachluy
igsnxmfkezbcjpdgwkrtaqtluy
posnxmfkfzbcjpdgwvrpaqhluy
iosnxmfkezbhjtdgwvrtaqhsuy
iosfxmfkezbcjpdwwvrtaqvluy
iosnxmfkehecjpdgwvrtaqoluy
iasnxmfkezbckpdgfvrtaqhluy
iosnxmfkezbwjpdggvrtaqhlmy
iosnxmfkezbcjpdgwvrkaqhbun
iosnxmikezbcjpdgwvrtaqhlnt
iosnxmfiazbcjpdgwvetaqhluy
iosnxmfkczbcjpfgwvrnaqhluy
iosnxmfkezkcjpdgsvrqaqhluy
iosnxmfkezbcspdgwvrtaqhxuc
iosnxmfdezbcjpdgwzrteqhluy
qosnxmrkezbcjpdgwvrtaqhlpy
iosnxmfkpabcjpdywvrtawhluy
ojsnxmfkezbcjpdgwvrtiqhluy
iosrxmfkezbcjpdgdvrtaqhlmy
iosnxmfkezbcnqdgwvrtayhluy
ionnxmfkezbcjpdgwvrsaehluy
iosnxmfkezbcjpdgwvrtmqhpuk
ifsnxmfkezbcjpdpwvrtaqhluf
insnxmfkezbcjpdgwrrtaqhmuy
iosnxmfxezbcjpdjwvrfaqhluy
iojnxmbkezccjpdgwvrtaqhluy
iosnomlkezbcjpdgwvotaqhluy
iosnamfkezbcjpdgwvrhqqhluy
iksnxmfkezbbjrdgwvrtaqhluy
iosnfmfkezbcjpdgwvrtaqhyay
iosnxmzkezbcjpdayvrtaqhluy
iosnxmfkezbcwpdgwbrtaqhlut
iosnxmfkezccjpdgivrtaqhbuy
iosuxmfkezbcjgdgwvrtaqhvuy
ipsnxmfkezbcjpaiwvrtaqhluy
iisnxmfkezbcjpdgpvrtaqqluy
ihsnxmfkezbcspdgwvrtahhluy
imsnxmfkezbcjpdgwvrtaqhkly
josnxmfkezbpjpdgwvttaqhluy
bosnxyfkezmcjpdgwvrtaqhluy
iosnxmfkezbcjpkgwvrtkqhjuy
iosnxmfkezbcjpdgwfrgaqfluy
rosnxmfkqzbcjpdgwvxtaqhluy
iosnxmfkezbcjpdgwlrwaqhluu
yysnxmfkezbcjpdgwvrtaxhluy
iosnxmpkezbcjldgwvrtaqoluy
gosnxmfkezrcjpdgwvrtarhluy
iosnxmfrezbcjrdmwvrtaqhluy
iosnxmfkekbcjpdgpvrtaqhyuy
iosbemfkezbcjpdgwdrtaqhluy
iosnxmfkezucjpdgwvatamhluy
ioanfmfkwzbcjpdgwvrtaqhluy
iosnxphkezbcjpdgwvrtaqhlly
ioynxmfkezbcjvbgwvrtaqhluy
iosnnmfkwzbcjpdgwvrtaqbluy
iosnxmfjezbcjpkgwtrtaqhluy
iosexmfkezbcjpdgwvrtmshluy
irsnxmwkezbcjpdgwvotaqhluy
iosnxmfkezpcjpdgwvrlaqkluy
iosnxmfkezbcjpwgwvroaqkluy
iosnxmfkizbcjpdgwvrtaqxlay
ioszxmfkezbcjpdgwertrqhluy
iosnxmfkczscjpdgwvrtcqhluy
iosnxmfkedbcjpdgwirtaqhliy
iosgxmfpezbcjpdgwvvtaqhluy
iownxmfiezbcjpdgwvrtajhluy
iosnxmfkezbejudgwvrqaqhluy
iomnpmfkezbcjpdgwvwtaqhluy
ioshxmfkecbcjpdgwfrtaqhluy
iosnxmfkezmcjpdgwzrtaqkluy
iownxdfkezdcjpdgwvrtaqhluy
iosnxmfjezbcjpdgwrotaqhluy
roknxmfkezbcjpdgwxrtaqhluy
iosnxmfkeibcjpdgovrtaqhloy
ifsnxmfkelbcjpdgwvrcaqhluy
iosnamfuezbcjpdwwvrtaqhluy
rssnxmfkeebcjpdgwvrtaqhluy
iosnomfkjzbcjpdgwvrtaqhlun
iosnxmfuezbcjpdgwfjtaqhluy
iosnxzfkezbcjpdewvrtaqhlfy
iosnxmfkezbcjpdgwvrtzqhlgr
iosixmfkezbcjpdgwvrkaqhlut
issnxmfkezbdjpdpwvrtaqhluy
iosnxmfrezbcjpdgwkrtaghluy
iysnxmfkezbcjpdgwrrtmqhluy
iosoxmfkezbcjpdgwjrtaqhlua
eosnxmfkezvcjpdgwvztaqhluy
iosmxmckezbcjpdgwvrtaqhlay
iosnxmfkezbcjodgwvrtaqhlma
josnxwftezbcjpdgwvrtaqhluy
iosnxjfkepbcjpdgwvrtaqhlsy
iosnnmfkezbcjpdgwvriaqhnuy
iosnxofkezbcupdgwvrtayhluy
iosnxmfkezbcjpddwvroaqhluz
iosnomfkezbcapdhwvrtaqhluy
iosixmfkezycjpdgwvrtaqhruy
iosnwefkezbcjpdgwvrtaqcluy
iosnxmfkvzbcbpdgwvrhaqhluy
insnxmfkezbczpdgwvrtajhluy
iosnxrfkelbcjpdgwvrtaqhluf
iosnxmfkezbcjpdgwsrtaqhzud
iosnxmfyvzbcjpdgwyrtaqhluy
"""

def read_data(data):
	twos = 0
	threes = 0
	for line in data.split():
		check_two = True
		check_three = True
		d = collections.defaultdict(int)
		for char in line:
			d[char] += 1
		for char in d:
			if d[char] == 3:
				if check_three:
					print "Is 3"
					threes += 1
					check_three = False
				else: 
					print "Already found a three in this set.  Moving on."
			elif d[char] == 2:
				if check_two:
					print "Is 2"
					twos += 1
					check_two = False
				else:
					print "already found a two in this set.  Moving on."
			elif d[char] < 2:
				print "Ones don't count."
	print "Checksum is: %i"  % (twos * threes)

if __name__ == "__main__":
	import collections
	read_data(data)